// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSwapOut = "swap_outs"

// SwapOut mapped from table <swap_outs>
type SwapOut struct {
	ID                 int64       `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;<-:create" json:"id"`
	SwapID             string      `gorm:"column:swap_id;type:text;not null" json:"swap_id"`
	Status             SwapStatus  `gorm:"column:status;type:swap_status;not null" json:"status"`
	AmountSats         int64       `gorm:"column:amount_sats;type:bigint;not null" json:"amount_sats"`
	DestinationAddress string      `gorm:"column:destination_address;type:text;not null" json:"destination_address"`
	ServiceFeeSats     int64       `gorm:"column:service_fee_sats;type:bigint;not null" json:"service_fee_sats"`
	OnchainFeeSats     int64       `gorm:"column:onchain_fee_sats;type:bigint;not null" json:"onchain_fee_sats"`
	OffchainFeeSats    int64       `gorm:"column:offchain_fee_sats;type:bigint;not null" json:"offchain_fee_sats"`
	DestinationChain   Chain       `gorm:"column:destination_chain;type:chain_enum;not null" json:"destination_chain"`
	ClaimPubkey        string      `gorm:"column:claim_pubkey;type:text;not null" json:"claim_pubkey"`
	PaymentRequest     string      `gorm:"column:payment_request;type:text;not null" json:"payment_request"`
	Description        string      `gorm:"column:description;type:text;not null" json:"description"`
	MaxRoutingFeeRatio float64     `gorm:"column:max_routing_fee_ratio;type:numeric;not null" json:"max_routing_fee_ratio"`
	Outcome            SwapOutcome `gorm:"column:outcome;type:swap_outcome;not null" json:"outcome"`
}

// TableName SwapOut's table name
func (*SwapOut) TableName() string {
	return TableNameSwapOut
}
