// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: 40swapd.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message definitions
type SwapOutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chain       string `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	InputAmount int32  `protobuf:"varint,2,opt,name=inputAmount,proto3" json:"inputAmount,omitempty"`
}

func (x *SwapOutRequest) Reset() {
	*x = SwapOutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file__40swapd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwapOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapOutRequest) ProtoMessage() {}

func (x *SwapOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file__40swapd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapOutRequest.ProtoReflect.Descriptor instead.
func (*SwapOutRequest) Descriptor() ([]byte, []int) {
	return file__40swapd_proto_rawDescGZIP(), []int{0}
}

func (x *SwapOutRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *SwapOutRequest) GetInputAmount() int32 {
	if x != nil {
		return x.InputAmount
	}
	return 0
}

type SwapOutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SwapOutResponse) Reset() {
	*x = SwapOutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file__40swapd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwapOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapOutResponse) ProtoMessage() {}

func (x *SwapOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file__40swapd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapOutResponse.ProtoReflect.Descriptor instead.
func (*SwapOutResponse) Descriptor() ([]byte, []int) {
	return file__40swapd_proto_rawDescGZIP(), []int{1}
}

var File__40swapd_proto protoreflect.FileDescriptor

var file__40swapd_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x34, 0x30, 0x73, 0x77, 0x61, 0x70, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x48, 0x0a, 0x0e, 0x53, 0x77, 0x61, 0x70, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x77, 0x61,
	0x70, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x3b, 0x0a, 0x0b,
	0x53, 0x77, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x53,
	0x77, 0x61, 0x70, 0x4f, 0x75, 0x74, 0x12, 0x0f, 0x2e, 0x53, 0x77, 0x61, 0x70, 0x4f, 0x75, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x53, 0x77, 0x61, 0x70, 0x4f, 0x75,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file__40swapd_proto_rawDescOnce sync.Once
	file__40swapd_proto_rawDescData = file__40swapd_proto_rawDesc
)

func file__40swapd_proto_rawDescGZIP() []byte {
	file__40swapd_proto_rawDescOnce.Do(func() {
		file__40swapd_proto_rawDescData = protoimpl.X.CompressGZIP(file__40swapd_proto_rawDescData)
	})
	return file__40swapd_proto_rawDescData
}

var file__40swapd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file__40swapd_proto_goTypes = []interface{}{
	(*SwapOutRequest)(nil),  // 0: SwapOutRequest
	(*SwapOutResponse)(nil), // 1: SwapOutResponse
}
var file__40swapd_proto_depIdxs = []int32{
	0, // 0: SwapService.SwapOut:input_type -> SwapOutRequest
	1, // 1: SwapService.SwapOut:output_type -> SwapOutResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file__40swapd_proto_init() }
func file__40swapd_proto_init() {
	if File__40swapd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file__40swapd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwapOutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__40swapd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwapOutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file__40swapd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file__40swapd_proto_goTypes,
		DependencyIndexes: file__40swapd_proto_depIdxs,
		MessageInfos:      file__40swapd_proto_msgTypes,
	}.Build()
	File__40swapd_proto = out.File
	file__40swapd_proto_rawDesc = nil
	file__40swapd_proto_goTypes = nil
	file__40swapd_proto_depIdxs = nil
}
