// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: 40swapd.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum definition
type Chain int32

const (
	Chain_BITCOIN Chain = 0
	Chain_LIQUID  Chain = 1
)

// Enum value maps for Chain.
var (
	Chain_name = map[int32]string{
		0: "BITCOIN",
		1: "LIQUID",
	}
	Chain_value = map[string]int32{
		"BITCOIN": 0,
		"LIQUID":  1,
	}
)

func (x Chain) Enum() *Chain {
	p := new(Chain)
	*p = x
	return p
}

func (x Chain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Chain) Descriptor() protoreflect.EnumDescriptor {
	return file__40swapd_proto_enumTypes[0].Descriptor()
}

func (Chain) Type() protoreflect.EnumType {
	return &file__40swapd_proto_enumTypes[0]
}

func (x Chain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Chain.Descriptor instead.
func (Chain) EnumDescriptor() ([]byte, []int) {
	return file__40swapd_proto_rawDescGZIP(), []int{0}
}

// Message definitions
type SwapOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         Chain                  `protobuf:"varint,1,opt,name=chain,proto3,enum=Chain" json:"chain,omitempty"`
	InputAmount   int32                  `protobuf:"varint,2,opt,name=inputAmount,proto3" json:"inputAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapOutRequest) Reset() {
	*x = SwapOutRequest{}
	mi := &file__40swapd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapOutRequest) ProtoMessage() {}

func (x *SwapOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file__40swapd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapOutRequest.ProtoReflect.Descriptor instead.
func (*SwapOutRequest) Descriptor() ([]byte, []int) {
	return file__40swapd_proto_rawDescGZIP(), []int{0}
}

func (x *SwapOutRequest) GetChain() Chain {
	if x != nil {
		return x.Chain
	}
	return Chain_BITCOIN
}

func (x *SwapOutRequest) GetInputAmount() int32 {
	if x != nil {
		return x.InputAmount
	}
	return 0
}

type SwapOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapOutResponse) Reset() {
	*x = SwapOutResponse{}
	mi := &file__40swapd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapOutResponse) ProtoMessage() {}

func (x *SwapOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file__40swapd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapOutResponse.ProtoReflect.Descriptor instead.
func (*SwapOutResponse) Descriptor() ([]byte, []int) {
	return file__40swapd_proto_rawDescGZIP(), []int{1}
}

var File__40swapd_proto protoreflect.FileDescriptor

var file__40swapd_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x34, 0x30, 0x73, 0x77, 0x61, 0x70, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x50, 0x0a, 0x0e, 0x53, 0x77, 0x61, 0x70, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x06, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12,
	0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x77, 0x61, 0x70, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x20, 0x0a, 0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x0b, 0x0a,
	0x07, 0x42, 0x49, 0x54, 0x43, 0x4f, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x49,
	0x51, 0x55, 0x49, 0x44, 0x10, 0x01, 0x32, 0x3b, 0x0a, 0x0b, 0x53, 0x77, 0x61, 0x70, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x53, 0x77, 0x61, 0x70, 0x4f, 0x75, 0x74,
	0x12, 0x0f, 0x2e, 0x53, 0x77, 0x61, 0x70, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x53, 0x77, 0x61, 0x70, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file__40swapd_proto_rawDescOnce sync.Once
	file__40swapd_proto_rawDescData []byte
)

func file__40swapd_proto_rawDescGZIP() []byte {
	file__40swapd_proto_rawDescOnce.Do(func() {
		file__40swapd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file__40swapd_proto_rawDesc), len(file__40swapd_proto_rawDesc)))
	})
	return file__40swapd_proto_rawDescData
}

var file__40swapd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file__40swapd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file__40swapd_proto_goTypes = []any{
	(Chain)(0),              // 0: Chain
	(*SwapOutRequest)(nil),  // 1: SwapOutRequest
	(*SwapOutResponse)(nil), // 2: SwapOutResponse
}
var file__40swapd_proto_depIdxs = []int32{
	0, // 0: SwapOutRequest.chain:type_name -> Chain
	1, // 1: SwapService.SwapOut:input_type -> SwapOutRequest
	2, // 2: SwapService.SwapOut:output_type -> SwapOutResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file__40swapd_proto_init() }
func file__40swapd_proto_init() {
	if File__40swapd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file__40swapd_proto_rawDesc), len(file__40swapd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file__40swapd_proto_goTypes,
		DependencyIndexes: file__40swapd_proto_depIdxs,
		EnumInfos:         file__40swapd_proto_enumTypes,
		MessageInfos:      file__40swapd_proto_msgTypes,
	}.Build()
	File__40swapd_proto = out.File
	file__40swapd_proto_goTypes = nil
	file__40swapd_proto_depIdxs = nil
}
