alias 40swap-bitcoin-cli='docker exec --user bitcoin 40swap_bitcoind  bitcoin-cli -regtest'
alias 40swap-lsp-lncli='docker exec -it 40swap_lnd_lsp lncli -n regtest'
alias 40swap-user-lncli='docker exec -it 40swap_lnd_user lncli -n regtest'
alias 40swap-alice-lncli='docker exec -it 40swap_lnd_alice lncli -n regtest'
alias 40swap-elements-cli='docker exec -it 40swap_elements elements-cli'

# Aditional nodes for big network setup
alias 40swap-bob-lncli='docker exec -it 40swap_lnd_bob lncli -n regtest'
alias 40swap-charlie-lncli='docker exec -it 40swap_lnd_charlie lncli -n regtest'
alias 40swap-david-lncli='docker exec -it 40swap_lnd_david lncli -n regtest'
alias 40swap-eve-lncli='docker exec -it 40swap_lnd_eve lncli -n regtest'
alias 40swap-frank-lncli='docker exec -it 40swap_lnd_frank lncli -n regtest'
alias 40swap-grace-lncli='docker exec -it 40swap_lnd_grace lncli -n regtest'
alias 40swap-henry-lncli='docker exec -it 40swap_lnd_henry lncli -n regtest'
alias 40swap-iris-lncli='docker exec -it 40swap_lnd_iris lncli -n regtest'
alias 40swap-jack-lncli='docker exec -it 40swap_lnd_jack lncli -n regtest'