// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/40acres/40swap/daemon/swaps (interfaces: ClientInterface)
//
// Generated by this command:
//
//	mockgen -destination=mock.go -package=swaps . ClientInterface
//

// Package swaps is a generated GoMock package.
package swaps

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
	isgomock struct{}
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// CreateSwapIn mocks base method.
func (m *MockClientInterface) CreateSwapIn(ctx context.Context, req *CreateSwapInRequest) (*SwapInResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSwapIn", ctx, req)
	ret0, _ := ret[0].(*SwapInResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSwapIn indicates an expected call of CreateSwapIn.
func (mr *MockClientInterfaceMockRecorder) CreateSwapIn(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSwapIn", reflect.TypeOf((*MockClientInterface)(nil).CreateSwapIn), ctx, req)
}

// CreateSwapOut mocks base method.
func (m *MockClientInterface) CreateSwapOut(ctx context.Context, swapReq CreateSwapOutRequest) (*SwapOutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSwapOut", ctx, swapReq)
	ret0, _ := ret[0].(*SwapOutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSwapOut indicates an expected call of CreateSwapOut.
func (mr *MockClientInterfaceMockRecorder) CreateSwapOut(ctx, swapReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSwapOut", reflect.TypeOf((*MockClientInterface)(nil).CreateSwapOut), ctx, swapReq)
}

// GetConfiguration mocks base method.
func (m *MockClientInterface) GetConfiguration(ctx context.Context) (*ConfigurationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfiguration", ctx)
	ret0, _ := ret[0].(*ConfigurationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfiguration indicates an expected call of GetConfiguration.
func (mr *MockClientInterfaceMockRecorder) GetConfiguration(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfiguration", reflect.TypeOf((*MockClientInterface)(nil).GetConfiguration), ctx)
}

// GetSwapIn mocks base method.
func (m *MockClientInterface) GetSwapIn(ctx context.Context, swapId string) (*SwapInResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSwapIn", ctx, swapId)
	ret0, _ := ret[0].(*SwapInResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSwapIn indicates an expected call of GetSwapIn.
func (mr *MockClientInterfaceMockRecorder) GetSwapIn(ctx, swapId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSwapIn", reflect.TypeOf((*MockClientInterface)(nil).GetSwapIn), ctx, swapId)
}

// GetSwapOut mocks base method.
func (m *MockClientInterface) GetSwapOut(ctx context.Context, swapId string) (*SwapOutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSwapOut", ctx, swapId)
	ret0, _ := ret[0].(*SwapOutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSwapOut indicates an expected call of GetSwapOut.
func (mr *MockClientInterfaceMockRecorder) GetSwapOut(ctx, swapId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSwapOut", reflect.TypeOf((*MockClientInterface)(nil).GetSwapOut), ctx, swapId)
}
