services:
  postgres:
    image: "postgres:16.4"
    container_name: 40swap_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "40swap"
      POSTGRES_PASSWORD: "40swap"
      POSTGRES_DB: "40swap"
  cloudbeaver:
    image: dbeaver/cloudbeaver:22.2.5
    container_name: 40swap_cloudbeaver
    volumes:
      - ./cloudbeaver-data-sources.json:/opt/cloudbeaver/conf/initial-data-sources.conf
      - ./cloudbeaver.auto.conf:/opt/cloudbeaver/conf/.cloudbeaver.auto.conf
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    ports:
      - 8978:8978
  bitcoind:
    image: ruimarinho/bitcoin-core:24.0.1
    container_name: 40swap_bitcoind
    command:
      -printtoconsole
      -regtest=1
      -rpcbind=0.0.0.0
      -rpcport=18443
      -rpcallowip=0.0.0.0/0
      -rpcauth=40swap:5604308b0303bc9e98f790c8edfb18fd$$bfdfba8951c6cc9c06ad5934ff176e7e031109e6afe5413270f295ee45dd4d66
      -whitelist=0.0.0.0/0
      -whitebind=0.0.0.0:18333
      -txindex=1
      -server=1
      -zmqpubrawblock=tcp://0.0.0.0:28334
      -zmqpubrawtx=tcp://0.0.0.0:28335
    volumes:
      - bitcoind-data:/home/bitcoin/.bitcoin
    expose:
      - "18332"
      - "18333"
      - "18443"
  lnd-lsp:
    image: lightninglabs/lnd:v0.18.2-beta
    container_name: 40swap_lnd_lsp
    command: >-
      --noseedbackup --trickledelay=5000 --alias=40swap-lsp --externalip=lnd-lsp
      --tlsextradomain=lnd-lsp
      --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080
      --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=bitcoind --bitcoind.rpcuser=40swap
      --bitcoind.rpcpass=pass
      --bitcoind.zmqpubrawblock=tcp://bitcoind:28334
      --bitcoind.zmqpubrawtx=tcp://bitcoind:28335
      --maxpendingchannels=20
      --gossip.channel-update-interval=10s
    restart: always
    depends_on:
      - "bitcoind"
    volumes:
      - lnd-lsp-data:/root/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '10002:10009'
  lnd-user:
    image: lightninglabs/lnd:v0.18.2-beta
    container_name: 40swap_lnd_user
    command: >-
      --noseedbackup --trickledelay=5000 --alias=40swap-user --externalip=lnd-user
      --tlsextradomain=lnd-user
      --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080
      --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=bitcoind --bitcoind.rpcuser=40swap
      --bitcoind.rpcpass=pass
      --bitcoind.zmqpubrawblock=tcp://bitcoind:28334
      --bitcoind.zmqpubrawtx=tcp://bitcoind:28335
      --maxpendingchannels=20
      --gossip.channel-update-interval=10s
    restart: always
    depends_on:
      - "bitcoind"
    volumes:
      - lnd-user-data:/root/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
  lnd-alice:
    image: lightninglabs/lnd:v0.18.2-beta
    container_name: 40swap_lnd_alice
    command: >-
      --noseedbackup --trickledelay=5000 --alias=alice --externalip=lnd-alice
      --tlsextradomain=lnd-alice
      --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080
      --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=bitcoind --bitcoind.rpcuser=40swap
      --bitcoind.rpcpass=pass
      --bitcoind.zmqpubrawblock=tcp://bitcoind:28334
      --bitcoind.zmqpubrawtx=tcp://bitcoind:28335
      --maxpendingchannels=20
      --gossip.channel-update-interval=10s
    restart: always
    depends_on:
      - "bitcoind"
    volumes:
      - lnd-alice-data:/root/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
  nbxplorer:
    image: nicolasdorier/nbxplorer:2.3.62
    container_name: 40swap_nbxplorer
    ports:
      - 32838:32838
    depends_on:
      - postgres
      - bitcoind
    restart: unless-stopped
    environment:
      NBXPLORER_NETWORK: regtest
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_NOAUTH: 1
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:18443/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:18333
      NBXPLORER_POSTGRES: Host=postgres;Port=5432;Database=40swap;Username=40swap;Password=40swap
      NBXPLORER_BTCRPCUSER: "40swap"
      NBXPLORER_BTCRPCPASSWORD: "pass"
      NBXPLORER_MAXGAPSIZE: 400
      NBXPLORER_MINGAPSIZE: 300
    volumes:
      - "nbxplorer-data:/datadir"
      - "bitcoind-data:/root/.bitcoin"
    links:
      - bitcoind
  rtl-user:
    container_name: 40swap_rtl_user
    image: shahanafarooqui/rtl:v0.15.2
    restart: unless-stopped
    depends_on:
      - lnd-user
    volumes:
      - lnd-user-data:/shared:ro
      - rtl-user-data:/database
    ports:
      - 7082:7082
    environment:
      PORT: 7082
      HOST: 0.0.0.0
      MACAROON_PATH: /shared/data/chain/bitcoin/regtest
      LN_SERVER_URL: https://lnd-user:8080
      CONFIG_PATH: ''
      LN_IMPLEMENTATION: LND
      RTL_SSO: 0
      RTL_COOKIE_PATH: ''
      LOGOUT_REDIRECT_LINK: ''
      RTL_CONFIG_PATH: /RTL
      BITCOIND_CONFIG_PATH: ''
      CHANNEL_BACKUP_PATH: /shared/lnd/backup
      ENABLE_OFFERS: false
      ENABLE_PEERSWAP: false
  rtl-lsp:
    container_name: 40swap_rtl_lsp
    image: shahanafarooqui/rtl:v0.15.2
    restart: unless-stopped
    depends_on:
      - lnd-lsp
    volumes:
      - lnd-lsp-data:/shared:ro
      - rtl-lsp-data:/database
    ports:
      - 7083:7083
    environment:
      PORT: 7083
      HOST: 0.0.0.0
      MACAROON_PATH: /shared/data/chain/bitcoin/regtest
      LN_SERVER_URL: https://lnd-lsp:8080
      CONFIG_PATH: ''
      LN_IMPLEMENTATION: LND
      RTL_SSO: 0
      RTL_COOKIE_PATH: ''
      LOGOUT_REDIRECT_LINK: ''
      RTL_CONFIG_PATH: /RTL
      BITCOIND_CONFIG_PATH: ''
      CHANNEL_BACKUP_PATH: /shared/lnd/backup
      ENABLE_OFFERS: false
      ENABLE_PEERSWAP: false
  mempool-frontend:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "mempool-backend"
    image: mempool/frontend:latest
    container_name: 40swap_mempool_frontend
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for mempool-db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 7084:8080
#  mempool-backend:
#    environment:
#      MEMPOOL_BACKEND: "electrum"
#      CORE_RPC_HOST: "bitcoind"
#      CORE_RPC_PORT: "18443"
#      CORE_RPC_USERNAME: "40swap"
#      CORE_RPC_PASSWORD: "pass"
#      DATABASE_ENABLED: "true"
#      DATABASE_HOST: "mempool-db"
#      DATABASE_DATABASE: "mempool"
#      DATABASE_USERNAME: "mempool"
#      DATABASE_PASSWORD: "mempool"
#      STATISTICS_ENABLED: "true"
#      ELECTRUM_HOST: "electrumx"
#      ELECTRUM_PORT: "50001"
#      ELECTRUM_TLS_ENABLED: "false"
#    image: mempool/backend:latest
#    container_name: 40swap_mempool_backend
#    user: "1000:1000"
#    restart: on-failure
#    stop_grace_period: 1m
#    command: "./wait-for-it.sh mempool-db:3306 --timeout=720 --strict -- ./start.sh"
#    depends_on:
#      - bitcoind
#      - mempool-db
#    volumes:
#      - mempool-backend-data:/backend/cache
#  mempool-db:
#    environment:
#      MYSQL_DATABASE: "mempool"
#      MYSQL_USER: "mempool"
#      MYSQL_PASSWORD: "mempool"
#      MYSQL_ROOT_PASSWORD: "admin"
#    image: mariadb:10.5.8
#    container_name: 40swap_mempool_db
#    restart: on-failure
#    stop_grace_period: 1m
#    volumes:
#      - mempool-db-data:/var/lib/mysql
#  electrumx:
#    image: andgohq/electrumx:1.8.7
#    container_name: 40swap_electrumx
#    depends_on:
#      - "bitcoind"
#    command: [ "wait-for-it.sh", "bitcoind:18443", "--", "init" ]
#    ports:
#      - "51002:50002"
#      - "51001:50001"
#    expose:
#      - "50001"
#      - "50002"
#    volumes:
#      - electrumx-data:/data
#    environment:
#      # bitcoind is valid
#      - DAEMON_URL=http://40swap:pass@bitcoind:18443
#      - COIN=BitcoinSegwit
#      - NET=regtest
#      # 127.0.0.1 or electrumx is valid for RPC_HOST
#      - RPC_HOST=electrumx
#      - RPC_PORT=18443
#      - HOST=electrumx
#      - TCP_PORT=50001
#      - SSL_PORT=50002
volumes:
  bitcoind-data:
  lnd-lsp-data:
  lnd-user-data:
  lnd-alice-data:
  nbxplorer-data:
  cloudbeaver-data:
  rtl-user-data:
  rtl-lsp-data:
  mempool-backend-data:
  mempool-db-data:
  electrumx-data: