name: Daemon

on:
  workflow_dispatch:

  push:
    branches:
      - "master"
    paths:
      - "daemon/**"
      - ".github/workflows/daemon.yaml"

    tags:
      - "*"

  pull_request:
    branches:
      - master
    paths:
      - "daemon/**"
      - ".github/workflows/daemon.yaml"
      
concurrency:
  # Cancel any previous workflows if they are from a PR or push.
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.23.1

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: daemon
          version: v1.61.0
          args: "--timeout=10m"

  go-test:
    runs-on: ubuntu-latest
    needs: go-lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Tests
        working-directory: daemon
        run:  go test ./...