name: Backend/Frontend CI
on:
  push:
    branches: ["master", "main"]
    tags:
      - "**"
    paths-ignore:
      - "daemon/**"
      - ".justfile"
      - "README.md"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME_FRONTEND: ${{ github.repository }}-swap-frontend
  IMAGE_NAME_BACKEND: ${{ github.repository }}-server-backend
jobs:
  integration-testing:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    steps:
      - uses: actions/checkout@v3
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install dependencies
        working-directory: server-backend
        run: npm ci
      - name: Run tests
        working-directory: server-backend
        run: npm test
  build:
    needs: integration-testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta-fe
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}
          tags: |
            type=raw,value={{branch}}-${{github.run_number}}-{{sha}}
            type=raw,value={{branch}}-${{github.run_number}}
      - name: Build and push frontend Docker image
        id: build-and-push-frontend
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: swap-frontend/docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-fe.outputs.tags }}
          labels: ${{ steps.meta-fe.outputs.labels }}
      - name: Extract Docker metadata
        id: meta-be
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}
          tags: |
            type=raw,value={{branch}}-${{github.run_number}}-{{sha}}
            type=raw,value={{branch}}-${{github.run_number}}
      - name: Build and push backend Docker image
        id: build-and-push-backend
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: server-backend/docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-be.outputs.tags }}
          labels: ${{ steps.meta-be.outputs.labels }}
